-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
      -   id: check-merge-conflict
      -   id: flake8
          args: [--max-line-length=100]
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
      -   id: black
          language_version: python3.7
-   repo: local
    hooks:
      -   id: unittests
          name: run unit test
          entry: pytest -v
          language: system
          types: [python]
          stages: [push, commit]
